/* 
 * Mantle API
 *
 * Most endpoints require authentication with an <strong>API key</strong><br><br>                                         You must first authenticate with your account by logging in your account on <strong><a target='_blank' href='https://www.mantleblockchain.com'/>mantleblockchain.com</a></strong>.<br>                                         Then, you will need to navigate to the <strong>My API Key</strong> page in the Settings section.<br>                                         You need to have the role administrator of your organization to generate an <strong>API Key</strong>.<br><br>                                         Then use this <strong>API Key</strong> in all your requests with the following header:<br><br>                                         <strong>[ x-api-key: API_KEY ]</strong><br><br>For more information on the different product and more, you can refer to the <a target='_blank' href='https://docs.mantleblockchain.com/v1.0/documentation/home'><strong>knowledge base</strong></a>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using mantle.lib.Client;
using mantle.lib.Api;
using mantle.lib.Model;

namespace mantle.lib.Test
{
    /// <summary>
    ///  Class for testing InvitationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class InvitationsApiTests
    {
        private InvitationsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new InvitationsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InvitationsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' InvitationsApi
            //Assert.IsInstanceOfType(typeof(InvitationsApi), instance, "instance is a InvitationsApi");
        }

        
        /// <summary>
        /// Test CreateInvitation
        /// </summary>
        [Test]
        public void CreateInvitationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //InvitationCreateRequest request = null;
            //var response = instance.CreateInvitation(xApiKey, request);
            //Assert.IsInstanceOf<Invitation> (response, "response is Invitation");
        }
        
        /// <summary>
        /// Test DeleteInvitation
        /// </summary>
        [Test]
        public void DeleteInvitationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string invitationId = null;
            //string xApiKey = null;
            //instance.DeleteInvitation(invitationId, xApiKey);
            
        }
        
        /// <summary>
        /// Test GetAllInvitations
        /// </summary>
        [Test]
        public void GetAllInvitationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //var response = instance.GetAllInvitations(xApiKey);
            //Assert.IsInstanceOf<List<Invitation>> (response, "response is List<Invitation>");
        }
        
        /// <summary>
        /// Test GetInvitationById
        /// </summary>
        [Test]
        public void GetInvitationByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string invitationId = null;
            //string xApiKey = null;
            //var response = instance.GetInvitationById(invitationId, xApiKey);
            //Assert.IsInstanceOf<InvitationSignUpResponse> (response, "response is InvitationSignUpResponse");
        }
        
    }

}
