/* 
 * Mantle API
 *
 * Most endpoints require authentication with an <strong>API key</strong><br><br>                                         You must first authenticate with your account by logging in your account on <strong><a target='_blank' href='https://www.mantleblockchain.com'/>mantleblockchain.com</a></strong>.<br>                                         Then, you will need to navigate to the <strong>My API Key</strong> page in the Settings section.<br>                                         You need to have the role administrator of your organization to generate an <strong>API Key</strong>.<br><br>                                         Then use this <strong>API Key</strong> in all your requests with the following header:<br><br>                                         <strong>[ x-api-key: API_KEY ]</strong><br><br>For more information on the different product and more, you can refer to the <a target='_blank' href='https://docs.mantleblockchain.com/v1.0/documentation/home'><strong>knowledge base</strong></a>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using mantle.lib.Client;
using mantle.lib.Api;
using mantle.lib.Model;

namespace mantle.lib.Test
{
    /// <summary>
    ///  Class for testing ProductsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ProductsApiTests
    {
        private ProductsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProductsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProductsApi
            //Assert.IsInstanceOfType(typeof(ProductsApi), instance, "instance is a ProductsApi");
        }

        
        /// <summary>
        /// Test GetAllProducts
        /// </summary>
        [Test]
        public void GetAllProductsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //var response = instance.GetAllProducts(xApiKey);
            //Assert.IsInstanceOf<List<ProductMenuOption>> (response, "response is List<ProductMenuOption>");
        }
        
        /// <summary>
        /// Test GetProductById
        /// </summary>
        [Test]
        public void GetProductByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string productId = null;
            //string xApiKey = null;
            //var response = instance.GetProductById(productId, xApiKey);
            //Assert.IsInstanceOf<ProductSubscription> (response, "response is ProductSubscription");
        }
        
        /// <summary>
        /// Test UpdateKeeperProduct
        /// </summary>
        [Test]
        public void UpdateKeeperProductTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string productId = null;
            //string xApiKey = null;
            //UpdateKeeperProductRequest request = null;
            //var response = instance.UpdateKeeperProduct(productId, xApiKey, request);
            //Assert.IsInstanceOf<KeeperProductSubscription> (response, "response is KeeperProductSubscription");
        }
        
        /// <summary>
        /// Test UpdateSealerProduct
        /// </summary>
        [Test]
        public void UpdateSealerProductTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string productId = null;
            //string xApiKey = null;
            //UpdateSealerProductRequest request = null;
            //var response = instance.UpdateSealerProduct(productId, xApiKey, request);
            //Assert.IsInstanceOf<SealerProductSubscription> (response, "response is SealerProductSubscription");
        }
        
        /// <summary>
        /// Test UpdateTrackerProduct
        /// </summary>
        [Test]
        public void UpdateTrackerProductTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string productId = null;
            //string xApiKey = null;
            //UpdateTrackerProductRequest request = null;
            //var response = instance.UpdateTrackerProduct(productId, xApiKey, request);
            //Assert.IsInstanceOf<TrackerProductSubscription> (response, "response is TrackerProductSubscription");
        }
        
    }

}
