/* 
 * Mantle API
 *
 * Most endpoints require authentication with an <strong>API key</strong><br><br>                                         You must first authenticate with your account by logging in your account on <strong><a target='_blank' href='https://www.mantleblockchain.com'/>mantleblockchain.com</a></strong>.<br>                                         Then, you will need to navigate to the <strong>My API Key</strong> page in the Settings section.<br>                                         You need to have the role administrator of your organization to generate an <strong>API Key</strong>.<br><br>                                         Then use this <strong>API Key</strong> in all your requests with the following header:<br><br>                                         <strong>[ x-api-key: API_KEY ]</strong><br><br>For more information on the different product and more, you can refer to the <a target='_blank' href='https://docs.mantleblockchain.com/v1.0/documentation/home'><strong>knowledge base</strong></a>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using mantle.lib.Client;
using mantle.lib.Model;

namespace mantle.lib.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBunkerApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// [STORAGE] Download a specific file
        /// </summary>
        /// <remarks>
        /// The file will be recreated from multiple shards than it&#39;s fingerprint will be compared with the on-chain reference to ensure integrity.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream DownloadFileById (string fileId, string productId, string xApiKey);

        /// <summary>
        /// [STORAGE] Download a specific file
        /// </summary>
        /// <remarks>
        /// The file will be recreated from multiple shards than it&#39;s fingerprint will be compared with the on-chain reference to ensure integrity.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> DownloadFileByIdWithHttpInfo (string fileId, string productId, string xApiKey);
        /// <summary>
        /// [STORAGE] Get all files
        /// </summary>
        /// <remarks>
        /// Get all the files stored in a Bunker.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>List&lt;BunkerFileResp&gt;</returns>
        List<BunkerFileResp> GetAllFilesIds (string productId, string xApiKey);

        /// <summary>
        /// [STORAGE] Get all files
        /// </summary>
        /// <remarks>
        /// Get all the files stored in a Bunker.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>ApiResponse of List&lt;BunkerFileResp&gt;</returns>
        ApiResponse<List<BunkerFileResp>> GetAllFilesIdsWithHttpInfo (string productId, string xApiKey);
        /// <summary>
        /// [STORAGE] Get status for the specific file id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>List&lt;BunkerFileResp&gt;</returns>
        List<BunkerFileResp> GetFileStatus (string fileId, string productId, string xApiKey);

        /// <summary>
        /// [STORAGE] Get status for the specific file id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>ApiResponse of List&lt;BunkerFileResp&gt;</returns>
        ApiResponse<List<BunkerFileResp>> GetFileStatusWithHttpInfo (string fileId, string productId, string xApiKey);
        /// <summary>
        /// [STORAGE] Upload a file
        /// </summary>
        /// <remarks>
        /// Files are currently limited to 500 Megabytes (500MB) in size.   This will fragment the file and store it onto multiple cloud providers.  A fingerprint of the file will also be create and store on-chain for further integrity reference.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">The file to upload. How http file upload works: https://goo.gl/UYQ2nX</param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <param name="displayName"> (optional)</param>
        /// <returns>BunkerCreateFileResp</returns>
        BunkerCreateFileResp PostFile (System.IO.Stream file, string productId, string xApiKey, string displayName = null);

        /// <summary>
        /// [STORAGE] Upload a file
        /// </summary>
        /// <remarks>
        /// Files are currently limited to 500 Megabytes (500MB) in size.   This will fragment the file and store it onto multiple cloud providers.  A fingerprint of the file will also be create and store on-chain for further integrity reference.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">The file to upload. How http file upload works: https://goo.gl/UYQ2nX</param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <param name="displayName"> (optional)</param>
        /// <returns>ApiResponse of BunkerCreateFileResp</returns>
        ApiResponse<BunkerCreateFileResp> PostFileWithHttpInfo (System.IO.Stream file, string productId, string xApiKey, string displayName = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// [STORAGE] Download a specific file
        /// </summary>
        /// <remarks>
        /// The file will be recreated from multiple shards than it&#39;s fingerprint will be compared with the on-chain reference to ensure integrity.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> DownloadFileByIdAsync (string fileId, string productId, string xApiKey);

        /// <summary>
        /// [STORAGE] Download a specific file
        /// </summary>
        /// <remarks>
        /// The file will be recreated from multiple shards than it&#39;s fingerprint will be compared with the on-chain reference to ensure integrity.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> DownloadFileByIdAsyncWithHttpInfo (string fileId, string productId, string xApiKey);
        /// <summary>
        /// [STORAGE] Get all files
        /// </summary>
        /// <remarks>
        /// Get all the files stored in a Bunker.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of List&lt;BunkerFileResp&gt;</returns>
        System.Threading.Tasks.Task<List<BunkerFileResp>> GetAllFilesIdsAsync (string productId, string xApiKey);

        /// <summary>
        /// [STORAGE] Get all files
        /// </summary>
        /// <remarks>
        /// Get all the files stored in a Bunker.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of ApiResponse (List&lt;BunkerFileResp&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<BunkerFileResp>>> GetAllFilesIdsAsyncWithHttpInfo (string productId, string xApiKey);
        /// <summary>
        /// [STORAGE] Get status for the specific file id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of List&lt;BunkerFileResp&gt;</returns>
        System.Threading.Tasks.Task<List<BunkerFileResp>> GetFileStatusAsync (string fileId, string productId, string xApiKey);

        /// <summary>
        /// [STORAGE] Get status for the specific file id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of ApiResponse (List&lt;BunkerFileResp&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<BunkerFileResp>>> GetFileStatusAsyncWithHttpInfo (string fileId, string productId, string xApiKey);
        /// <summary>
        /// [STORAGE] Upload a file
        /// </summary>
        /// <remarks>
        /// Files are currently limited to 500 Megabytes (500MB) in size.   This will fragment the file and store it onto multiple cloud providers.  A fingerprint of the file will also be create and store on-chain for further integrity reference.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">The file to upload. How http file upload works: https://goo.gl/UYQ2nX</param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <param name="displayName"> (optional)</param>
        /// <returns>Task of BunkerCreateFileResp</returns>
        System.Threading.Tasks.Task<BunkerCreateFileResp> PostFileAsync (System.IO.Stream file, string productId, string xApiKey, string displayName = null);

        /// <summary>
        /// [STORAGE] Upload a file
        /// </summary>
        /// <remarks>
        /// Files are currently limited to 500 Megabytes (500MB) in size.   This will fragment the file and store it onto multiple cloud providers.  A fingerprint of the file will also be create and store on-chain for further integrity reference.
        /// </remarks>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">The file to upload. How http file upload works: https://goo.gl/UYQ2nX</param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <param name="displayName"> (optional)</param>
        /// <returns>Task of ApiResponse (BunkerCreateFileResp)</returns>
        System.Threading.Tasks.Task<ApiResponse<BunkerCreateFileResp>> PostFileAsyncWithHttpInfo (System.IO.Stream file, string productId, string xApiKey, string displayName = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BunkerApi : IBunkerApi
    {
        private mantle.lib.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BunkerApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BunkerApi(String basePath)
        {
            this.Configuration = new mantle.lib.Client.Configuration { BasePath = basePath };

            ExceptionFactory = mantle.lib.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BunkerApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BunkerApi(mantle.lib.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = mantle.lib.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = mantle.lib.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public mantle.lib.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public mantle.lib.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// [STORAGE] Download a specific file The file will be recreated from multiple shards than it&#39;s fingerprint will be compared with the on-chain reference to ensure integrity.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream DownloadFileById (string fileId, string productId, string xApiKey)
        {
             ApiResponse<System.IO.Stream> localVarResponse = DownloadFileByIdWithHttpInfo(fileId, productId, xApiKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// [STORAGE] Download a specific file The file will be recreated from multiple shards than it&#39;s fingerprint will be compared with the on-chain reference to ensure integrity.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > DownloadFileByIdWithHttpInfo (string fileId, string productId, string xApiKey)
        {
            // verify the required parameter 'fileId' is set
            if (fileId == null)
                throw new ApiException(400, "Missing required parameter 'fileId' when calling BunkerApi->DownloadFileById");
            // verify the required parameter 'productId' is set
            if (productId == null)
                throw new ApiException(400, "Missing required parameter 'productId' when calling BunkerApi->DownloadFileById");
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
                throw new ApiException(400, "Missing required parameter 'xApiKey' when calling BunkerApi->DownloadFileById");

            var localVarPath = "/bunker/{productId}/files/{fileId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fileId != null) localVarPathParams.Add("fileId", this.Configuration.ApiClient.ParameterToString(fileId)); // path parameter
            if (productId != null) localVarPathParams.Add("productId", this.Configuration.ApiClient.ParameterToString(productId)); // path parameter
            if (xApiKey != null) localVarHeaderParams.Add("x-api-key", this.Configuration.ApiClient.ParameterToString(xApiKey)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DownloadFileById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// [STORAGE] Download a specific file The file will be recreated from multiple shards than it&#39;s fingerprint will be compared with the on-chain reference to ensure integrity.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> DownloadFileByIdAsync (string fileId, string productId, string xApiKey)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await DownloadFileByIdAsyncWithHttpInfo(fileId, productId, xApiKey);
             return localVarResponse.Data;

        }

        /// <summary>
        /// [STORAGE] Download a specific file The file will be recreated from multiple shards than it&#39;s fingerprint will be compared with the on-chain reference to ensure integrity.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> DownloadFileByIdAsyncWithHttpInfo (string fileId, string productId, string xApiKey)
        {
            // verify the required parameter 'fileId' is set
            if (fileId == null)
                throw new ApiException(400, "Missing required parameter 'fileId' when calling BunkerApi->DownloadFileById");
            // verify the required parameter 'productId' is set
            if (productId == null)
                throw new ApiException(400, "Missing required parameter 'productId' when calling BunkerApi->DownloadFileById");
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
                throw new ApiException(400, "Missing required parameter 'xApiKey' when calling BunkerApi->DownloadFileById");

            var localVarPath = "/bunker/{productId}/files/{fileId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fileId != null) localVarPathParams.Add("fileId", this.Configuration.ApiClient.ParameterToString(fileId)); // path parameter
            if (productId != null) localVarPathParams.Add("productId", this.Configuration.ApiClient.ParameterToString(productId)); // path parameter
            if (xApiKey != null) localVarHeaderParams.Add("x-api-key", this.Configuration.ApiClient.ParameterToString(xApiKey)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DownloadFileById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// [STORAGE] Get all files Get all the files stored in a Bunker.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>List&lt;BunkerFileResp&gt;</returns>
        public List<BunkerFileResp> GetAllFilesIds (string productId, string xApiKey)
        {
             ApiResponse<List<BunkerFileResp>> localVarResponse = GetAllFilesIdsWithHttpInfo(productId, xApiKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// [STORAGE] Get all files Get all the files stored in a Bunker.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>ApiResponse of List&lt;BunkerFileResp&gt;</returns>
        public ApiResponse< List<BunkerFileResp> > GetAllFilesIdsWithHttpInfo (string productId, string xApiKey)
        {
            // verify the required parameter 'productId' is set
            if (productId == null)
                throw new ApiException(400, "Missing required parameter 'productId' when calling BunkerApi->GetAllFilesIds");
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
                throw new ApiException(400, "Missing required parameter 'xApiKey' when calling BunkerApi->GetAllFilesIds");

            var localVarPath = "/bunker/{productId}/files";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (productId != null) localVarPathParams.Add("productId", this.Configuration.ApiClient.ParameterToString(productId)); // path parameter
            if (xApiKey != null) localVarHeaderParams.Add("x-api-key", this.Configuration.ApiClient.ParameterToString(xApiKey)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllFilesIds", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BunkerFileResp>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<BunkerFileResp>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BunkerFileResp>)));
        }

        /// <summary>
        /// [STORAGE] Get all files Get all the files stored in a Bunker.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of List&lt;BunkerFileResp&gt;</returns>
        public async System.Threading.Tasks.Task<List<BunkerFileResp>> GetAllFilesIdsAsync (string productId, string xApiKey)
        {
             ApiResponse<List<BunkerFileResp>> localVarResponse = await GetAllFilesIdsAsyncWithHttpInfo(productId, xApiKey);
             return localVarResponse.Data;

        }

        /// <summary>
        /// [STORAGE] Get all files Get all the files stored in a Bunker.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of ApiResponse (List&lt;BunkerFileResp&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<BunkerFileResp>>> GetAllFilesIdsAsyncWithHttpInfo (string productId, string xApiKey)
        {
            // verify the required parameter 'productId' is set
            if (productId == null)
                throw new ApiException(400, "Missing required parameter 'productId' when calling BunkerApi->GetAllFilesIds");
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
                throw new ApiException(400, "Missing required parameter 'xApiKey' when calling BunkerApi->GetAllFilesIds");

            var localVarPath = "/bunker/{productId}/files";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (productId != null) localVarPathParams.Add("productId", this.Configuration.ApiClient.ParameterToString(productId)); // path parameter
            if (xApiKey != null) localVarHeaderParams.Add("x-api-key", this.Configuration.ApiClient.ParameterToString(xApiKey)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAllFilesIds", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BunkerFileResp>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<BunkerFileResp>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BunkerFileResp>)));
        }

        /// <summary>
        /// [STORAGE] Get status for the specific file id 
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>List&lt;BunkerFileResp&gt;</returns>
        public List<BunkerFileResp> GetFileStatus (string fileId, string productId, string xApiKey)
        {
             ApiResponse<List<BunkerFileResp>> localVarResponse = GetFileStatusWithHttpInfo(fileId, productId, xApiKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// [STORAGE] Get status for the specific file id 
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>ApiResponse of List&lt;BunkerFileResp&gt;</returns>
        public ApiResponse< List<BunkerFileResp> > GetFileStatusWithHttpInfo (string fileId, string productId, string xApiKey)
        {
            // verify the required parameter 'fileId' is set
            if (fileId == null)
                throw new ApiException(400, "Missing required parameter 'fileId' when calling BunkerApi->GetFileStatus");
            // verify the required parameter 'productId' is set
            if (productId == null)
                throw new ApiException(400, "Missing required parameter 'productId' when calling BunkerApi->GetFileStatus");
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
                throw new ApiException(400, "Missing required parameter 'xApiKey' when calling BunkerApi->GetFileStatus");

            var localVarPath = "/bunker/{productId}/files/status/{fileId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fileId != null) localVarPathParams.Add("fileId", this.Configuration.ApiClient.ParameterToString(fileId)); // path parameter
            if (productId != null) localVarPathParams.Add("productId", this.Configuration.ApiClient.ParameterToString(productId)); // path parameter
            if (xApiKey != null) localVarHeaderParams.Add("x-api-key", this.Configuration.ApiClient.ParameterToString(xApiKey)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetFileStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BunkerFileResp>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<BunkerFileResp>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BunkerFileResp>)));
        }

        /// <summary>
        /// [STORAGE] Get status for the specific file id 
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of List&lt;BunkerFileResp&gt;</returns>
        public async System.Threading.Tasks.Task<List<BunkerFileResp>> GetFileStatusAsync (string fileId, string productId, string xApiKey)
        {
             ApiResponse<List<BunkerFileResp>> localVarResponse = await GetFileStatusAsyncWithHttpInfo(fileId, productId, xApiKey);
             return localVarResponse.Data;

        }

        /// <summary>
        /// [STORAGE] Get status for the specific file id 
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="fileId"></param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <returns>Task of ApiResponse (List&lt;BunkerFileResp&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<BunkerFileResp>>> GetFileStatusAsyncWithHttpInfo (string fileId, string productId, string xApiKey)
        {
            // verify the required parameter 'fileId' is set
            if (fileId == null)
                throw new ApiException(400, "Missing required parameter 'fileId' when calling BunkerApi->GetFileStatus");
            // verify the required parameter 'productId' is set
            if (productId == null)
                throw new ApiException(400, "Missing required parameter 'productId' when calling BunkerApi->GetFileStatus");
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
                throw new ApiException(400, "Missing required parameter 'xApiKey' when calling BunkerApi->GetFileStatus");

            var localVarPath = "/bunker/{productId}/files/status/{fileId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (fileId != null) localVarPathParams.Add("fileId", this.Configuration.ApiClient.ParameterToString(fileId)); // path parameter
            if (productId != null) localVarPathParams.Add("productId", this.Configuration.ApiClient.ParameterToString(productId)); // path parameter
            if (xApiKey != null) localVarHeaderParams.Add("x-api-key", this.Configuration.ApiClient.ParameterToString(xApiKey)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetFileStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BunkerFileResp>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<BunkerFileResp>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BunkerFileResp>)));
        }

        /// <summary>
        /// [STORAGE] Upload a file Files are currently limited to 500 Megabytes (500MB) in size.   This will fragment the file and store it onto multiple cloud providers.  A fingerprint of the file will also be create and store on-chain for further integrity reference.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">The file to upload. How http file upload works: https://goo.gl/UYQ2nX</param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <param name="displayName"> (optional)</param>
        /// <returns>BunkerCreateFileResp</returns>
        public BunkerCreateFileResp PostFile (System.IO.Stream file, string productId, string xApiKey, string displayName = null)
        {
             ApiResponse<BunkerCreateFileResp> localVarResponse = PostFileWithHttpInfo(file, productId, xApiKey, displayName);
             return localVarResponse.Data;
        }

        /// <summary>
        /// [STORAGE] Upload a file Files are currently limited to 500 Megabytes (500MB) in size.   This will fragment the file and store it onto multiple cloud providers.  A fingerprint of the file will also be create and store on-chain for further integrity reference.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">The file to upload. How http file upload works: https://goo.gl/UYQ2nX</param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <param name="displayName"> (optional)</param>
        /// <returns>ApiResponse of BunkerCreateFileResp</returns>
        public ApiResponse< BunkerCreateFileResp > PostFileWithHttpInfo (System.IO.Stream file, string productId, string xApiKey, string displayName = null)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new ApiException(400, "Missing required parameter 'file' when calling BunkerApi->PostFile");
            // verify the required parameter 'productId' is set
            if (productId == null)
                throw new ApiException(400, "Missing required parameter 'productId' when calling BunkerApi->PostFile");
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
                throw new ApiException(400, "Missing required parameter 'xApiKey' when calling BunkerApi->PostFile");

            var localVarPath = "/bunker/{productId}/files";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (productId != null) localVarPathParams.Add("productId", this.Configuration.ApiClient.ParameterToString(productId)); // path parameter
            if (xApiKey != null) localVarHeaderParams.Add("x-api-key", this.Configuration.ApiClient.ParameterToString(xApiKey)); // header parameter
            if (file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", file));
            if (displayName != null) localVarFormParams.Add("displayName", this.Configuration.ApiClient.ParameterToString(displayName)); // form parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BunkerCreateFileResp>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BunkerCreateFileResp) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BunkerCreateFileResp)));
        }

        /// <summary>
        /// [STORAGE] Upload a file Files are currently limited to 500 Megabytes (500MB) in size.   This will fragment the file and store it onto multiple cloud providers.  A fingerprint of the file will also be create and store on-chain for further integrity reference.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">The file to upload. How http file upload works: https://goo.gl/UYQ2nX</param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <param name="displayName"> (optional)</param>
        /// <returns>Task of BunkerCreateFileResp</returns>
        public async System.Threading.Tasks.Task<BunkerCreateFileResp> PostFileAsync (System.IO.Stream file, string productId, string xApiKey, string displayName = null)
        {
             ApiResponse<BunkerCreateFileResp> localVarResponse = await PostFileAsyncWithHttpInfo(file, productId, xApiKey, displayName);
             return localVarResponse.Data;

        }

        /// <summary>
        /// [STORAGE] Upload a file Files are currently limited to 500 Megabytes (500MB) in size.   This will fragment the file and store it onto multiple cloud providers.  A fingerprint of the file will also be create and store on-chain for further integrity reference.
        /// </summary>
        /// <exception cref="mantle.lib.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">The file to upload. How http file upload works: https://goo.gl/UYQ2nX</param>
        /// <param name="productId"></param>
        /// <param name="xApiKey"></param>
        /// <param name="displayName"> (optional)</param>
        /// <returns>Task of ApiResponse (BunkerCreateFileResp)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BunkerCreateFileResp>> PostFileAsyncWithHttpInfo (System.IO.Stream file, string productId, string xApiKey, string displayName = null)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new ApiException(400, "Missing required parameter 'file' when calling BunkerApi->PostFile");
            // verify the required parameter 'productId' is set
            if (productId == null)
                throw new ApiException(400, "Missing required parameter 'productId' when calling BunkerApi->PostFile");
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
                throw new ApiException(400, "Missing required parameter 'xApiKey' when calling BunkerApi->PostFile");

            var localVarPath = "/bunker/{productId}/files";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (productId != null) localVarPathParams.Add("productId", this.Configuration.ApiClient.ParameterToString(productId)); // path parameter
            if (xApiKey != null) localVarHeaderParams.Add("x-api-key", this.Configuration.ApiClient.ParameterToString(xApiKey)); // header parameter
            if (file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", file));
            if (displayName != null) localVarFormParams.Add("displayName", this.Configuration.ApiClient.ParameterToString(displayName)); // form parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BunkerCreateFileResp>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BunkerCreateFileResp) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BunkerCreateFileResp)));
        }

    }
}
