/* 
 * Mantle API
 *
 * Most endpoints require authentication with an <strong>API key</strong><br><br>                                         You must first authenticate with your account by logging in your account on <strong><a target='_blank' href='https://www.mantleblockchain.com'/>mantleblockchain.com</a></strong>.<br>                                         Then, you will need to navigate to the <strong>My API Key</strong> page in the Settings section.<br>                                         You need to have the role administrator of your organization to generate an <strong>API Key</strong>.<br><br>                                         Then use this <strong>API Key</strong> in all your requests with the following header:<br><br>                                         <strong>[ x-api-key: API_KEY ]</strong><br><br>For more information on the different product and more, you can refer to the <a target='_blank' href='https://docs.mantleblockchain.com/v1.0/documentation/home'><strong>knowledge base</strong></a>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace mantle.lib.Model
{
    /// <summary>
    /// TrackerAssetIssueBulkRequest
    /// </summary>
    [DataContract]
    public partial class TrackerAssetIssueBulkRequest :  IEquatable<TrackerAssetIssueBulkRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackerAssetIssueBulkRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TrackerAssetIssueBulkRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackerAssetIssueBulkRequest" /> class.
        /// </summary>
        /// <param name="AssetId">AssetId (required).</param>
        /// <param name="OwnedId">OwnedId.</param>
        /// <param name="RecipientEmail">RecipientEmail (required).</param>
        /// <param name="Amount">Amount (required).</param>
        /// <param name="MetaData">MetaData.</param>
        public TrackerAssetIssueBulkRequest(string AssetId = null, string OwnedId = null, string RecipientEmail = null, int? Amount = null, string MetaData = null)
        {
            // to ensure "AssetId" is required (not null)
            if (AssetId == null)
            {
                throw new InvalidDataException("AssetId is a required property for TrackerAssetIssueBulkRequest and cannot be null");
            }
            else
            {
                this.AssetId = AssetId;
            }
            // to ensure "RecipientEmail" is required (not null)
            if (RecipientEmail == null)
            {
                throw new InvalidDataException("RecipientEmail is a required property for TrackerAssetIssueBulkRequest and cannot be null");
            }
            else
            {
                this.RecipientEmail = RecipientEmail;
            }
            // to ensure "Amount" is required (not null)
            if (Amount == null)
            {
                throw new InvalidDataException("Amount is a required property for TrackerAssetIssueBulkRequest and cannot be null");
            }
            else
            {
                this.Amount = Amount;
            }
            this.OwnedId = OwnedId;
            this.MetaData = MetaData;
        }
        
        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [DataMember(Name="assetId", EmitDefaultValue=false)]
        public string AssetId { get; set; }
        /// <summary>
        /// Gets or Sets OwnedId
        /// </summary>
        [DataMember(Name="ownedId", EmitDefaultValue=false)]
        public string OwnedId { get; set; }
        /// <summary>
        /// Gets or Sets RecipientEmail
        /// </summary>
        [DataMember(Name="recipientEmail", EmitDefaultValue=false)]
        public string RecipientEmail { get; set; }
        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public int? Amount { get; set; }
        /// <summary>
        /// Gets or Sets MetaData
        /// </summary>
        [DataMember(Name="metaData", EmitDefaultValue=false)]
        public string MetaData { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TrackerAssetIssueBulkRequest {\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  OwnedId: ").Append(OwnedId).Append("\n");
            sb.Append("  RecipientEmail: ").Append(RecipientEmail).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  MetaData: ").Append(MetaData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TrackerAssetIssueBulkRequest);
        }

        /// <summary>
        /// Returns true if TrackerAssetIssueBulkRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of TrackerAssetIssueBulkRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TrackerAssetIssueBulkRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AssetId == other.AssetId ||
                    this.AssetId != null &&
                    this.AssetId.Equals(other.AssetId)
                ) && 
                (
                    this.OwnedId == other.OwnedId ||
                    this.OwnedId != null &&
                    this.OwnedId.Equals(other.OwnedId)
                ) && 
                (
                    this.RecipientEmail == other.RecipientEmail ||
                    this.RecipientEmail != null &&
                    this.RecipientEmail.Equals(other.RecipientEmail)
                ) && 
                (
                    this.Amount == other.Amount ||
                    this.Amount != null &&
                    this.Amount.Equals(other.Amount)
                ) && 
                (
                    this.MetaData == other.MetaData ||
                    this.MetaData != null &&
                    this.MetaData.Equals(other.MetaData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AssetId != null)
                    hash = hash * 59 + this.AssetId.GetHashCode();
                if (this.OwnedId != null)
                    hash = hash * 59 + this.OwnedId.GetHashCode();
                if (this.RecipientEmail != null)
                    hash = hash * 59 + this.RecipientEmail.GetHashCode();
                if (this.Amount != null)
                    hash = hash * 59 + this.Amount.GetHashCode();
                if (this.MetaData != null)
                    hash = hash * 59 + this.MetaData.GetHashCode();
                return hash;
            }
        }
    }

}
