/* 
 * Mantle API
 *
 * Most endpoints require authentication with an <strong>API key</strong><br><br>                                         You must first authenticate with your account by logging in your account on <strong><a target='_blank' href='https://www.mantleblockchain.com'/>mantleblockchain.com</a></strong>.<br>                                         Then, you will need to navigate to the <strong>My API Key</strong> page in the Settings section.<br>                                         You need to have the role administrator of your organization to generate an <strong>API Key</strong>.<br><br>                                         Then use this <strong>API Key</strong> in all your requests with the following header:<br><br>                                         <strong>[ x-api-key: API_KEY ]</strong><br><br>For more information on the different product and more, you can refer to the <a target='_blank' href='https://docs.mantleblockchain.com/v1.0/documentation/home'><strong>knowledge base</strong></a>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace mantle.lib.Model
{
    /// <summary>
    /// TrackerBatchTransferRequest
    /// </summary>
    [DataContract]
    public partial class TrackerBatchTransferRequest :  IEquatable<TrackerBatchTransferRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackerBatchTransferRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TrackerBatchTransferRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackerBatchTransferRequest" /> class.
        /// </summary>
        /// <param name="RecipientDisplayName">RecipientDisplayName (required).</param>
        /// <param name="Amount">Amount (required).</param>
        /// <param name="BatchIds">BatchIds (required).</param>
        public TrackerBatchTransferRequest(string RecipientDisplayName = null, int? Amount = null, List<string> BatchIds = null)
        {
            // to ensure "RecipientDisplayName" is required (not null)
            if (RecipientDisplayName == null)
            {
                throw new InvalidDataException("RecipientDisplayName is a required property for TrackerBatchTransferRequest and cannot be null");
            }
            else
            {
                this.RecipientDisplayName = RecipientDisplayName;
            }
            // to ensure "Amount" is required (not null)
            if (Amount == null)
            {
                throw new InvalidDataException("Amount is a required property for TrackerBatchTransferRequest and cannot be null");
            }
            else
            {
                this.Amount = Amount;
            }
            // to ensure "BatchIds" is required (not null)
            if (BatchIds == null)
            {
                throw new InvalidDataException("BatchIds is a required property for TrackerBatchTransferRequest and cannot be null");
            }
            else
            {
                this.BatchIds = BatchIds;
            }
        }
        
        /// <summary>
        /// Gets or Sets RecipientDisplayName
        /// </summary>
        [DataMember(Name="recipientDisplayName", EmitDefaultValue=false)]
        public string RecipientDisplayName { get; set; }
        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public int? Amount { get; set; }
        /// <summary>
        /// Gets or Sets BatchIds
        /// </summary>
        [DataMember(Name="batchIds", EmitDefaultValue=false)]
        public List<string> BatchIds { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TrackerBatchTransferRequest {\n");
            sb.Append("  RecipientDisplayName: ").Append(RecipientDisplayName).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  BatchIds: ").Append(BatchIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TrackerBatchTransferRequest);
        }

        /// <summary>
        /// Returns true if TrackerBatchTransferRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of TrackerBatchTransferRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TrackerBatchTransferRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.RecipientDisplayName == other.RecipientDisplayName ||
                    this.RecipientDisplayName != null &&
                    this.RecipientDisplayName.Equals(other.RecipientDisplayName)
                ) && 
                (
                    this.Amount == other.Amount ||
                    this.Amount != null &&
                    this.Amount.Equals(other.Amount)
                ) && 
                (
                    this.BatchIds == other.BatchIds ||
                    this.BatchIds != null &&
                    this.BatchIds.SequenceEqual(other.BatchIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.RecipientDisplayName != null)
                    hash = hash * 59 + this.RecipientDisplayName.GetHashCode();
                if (this.Amount != null)
                    hash = hash * 59 + this.Amount.GetHashCode();
                if (this.BatchIds != null)
                    hash = hash * 59 + this.BatchIds.GetHashCode();
                return hash;
            }
        }
    }

}
